DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE posts (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	caption VARCHAR NOT NULL,
	image_url VARCHAR(128) NOT NULL,
	cloudinary_id VARCHAR(128) NOT NULL
);

INSERT INTO posts (
caption
)
VALUES (
'is it trash?'
);